export { default as CompanyPhone } from "./CompanyPhone.vue"
export { default as CompanyLogo } from "./CompanyLogo.vue"
export { default as BackgroundWithSelection } from "./BackgroundWithSelection.vue"
export { default as RequestCall } from "./RequestCall.vue"
export { default as DroneVideo } from "./DroneVideo.vue"
export { default as YandexPanorama } from "./YandexPanorama.vue"
