export { default as HeroBlock } from "./Frame1HeroBlock"
export { default as MainInfo } from "./Frame2MainInfo"
export { default as ApartmentSelector } from "./Frame3ApartmentSelector"
export { default as DroneVideo } from "./Frame4DroneVideo"
export { default as AboutCompany } from "./Frame5AboutCompany"
export { default as MainMenu } from "./MainMenu"
