export { default as HeroBlock } from "./F1HeroBlock"
export { default as BuildingBack } from "./F2BuildingBack"
export { default as GenPlan } from "./F3GenPlan"
export { default as MainInfo } from "./F4MainInfo"
export { default as ApartmentSelector } from "./F5ApartmentSelector"
export { default as DroneVideo } from "./F6DroneVideo"
export { default as AboutCompany } from "./F7AboutCompany"
